Start documenting prioritary tasks.
ApolloTeam-dev/AROS pull request #32
Opened 2021-02-08 14:01 UTC by AlbertoGP

2021-02-08 14:26 UTC, MBeijer approved these changes

2021-02-08 17:00 UTC, AlbertoGP commented
The content is based on the discussion today with Gunnar and others in the Discord channel: https://discord.com/channels/726870908568076380/730698753513750539/808265391184412692

2021-03-20 13:59 UTC, MBeijer requested changes
Some things need to change due to `master-new` branch being renamed to `master` and `mkapollo.sh`-script being merged to master. :)

2021-03-20 13:59 UTC, MBeijer commented on docs/tasks/GFX-subsystem.md
> +- If you are using the [`mkapollo.sh`](https://github.com/ApolloTeam-dev/AROS/blob/v4-alynna/mkapollo.sh) script, `./mkapollo.sh kernel` suffices to build it. There are some improvements pending merg
mkapollo is merged to master now
```suggestion
- If you are using the [`mkapollo.sh`](https://github.com/ApolloTeam-dev/AROS/blob/master/mkapollo.sh) script, `./mkapollo.sh kernel` suffices to build it. 
```

2021-03-20 13:59 UTC, MBeijer commented on docs/tasks/IDE.md
> +- If you are using the [`mkapollo.sh`](https://github.com/ApolloTeam-dev/AROS/blob/v4-alynna/mkapollo.sh) script, `./mkapollo.sh kernel` suffices to build it. There are some improvements pending merg
```suggestion
- If you are using the [`mkapollo.sh`](https://github.com/ApolloTeam-dev/AROS/blob/v4-alynna/mkapollo.sh) script, `./mkapollo.sh kernel` suffices to build it.
```

2021-03-20 13:59 UTC, MBeijer commented on docs/tasks/IDE.md
> +- With the [`master-new`](https://github.com/ApolloTeam-dev/AROS) branch, which is the default, use `build_all.sh`.
```suggestion
- With the [`master`](https://github.com/ApolloTeam-dev/AROS) branch, which is the default, use `build_all.sh`.
```
master-new is now renamed master

2021-03-20 13:59 UTC, MBeijer commented on docs/tasks/GFX-subsystem.md
> +- With the [`master-new`](https://github.com/ApolloTeam-dev/AROS) branch, which is the default, use `build_all.sh`.
```suggestion
- With the [`master`](https://github.com/ApolloTeam-dev/AROS) branch, which is the default, use `build_all.sh`.
```

2021-03-20 13:59 UTC, MBeijer commented on docs/tasks.md
> +Do not forget the `--recursive` option with `git clone`!
```suggestion
**Do not forget the `--recursive` option with `git clone`!**
```

2021-03-20 13:59 UTC, MBeijer commented on docs/tasks/GFX-subsystem.md
> +Source code:
```suggestion
## Source code
```

2021-03-20 13:59 UTC, MBeijer commented on docs/tasks/GFX-subsystem.md
> +Documentation from AROS:
```suggestion
## Documentation from AROS
```

2021-03-20 13:59 UTC, MBeijer commented on docs/tasks/GFX-subsystem.md
> +- [`rom/graphics/`](https://github.com/ApolloTeam-dev/AROS/tree/master-new/rom/graphics/)
```suggestion
- [`rom/graphics/`](https://github.com/ApolloTeam-dev/AROS/tree/master/rom/graphics/)
```

2021-03-20 13:59 UTC, MBeijer commented on docs/tasks/IDE.md
> +- [`rom/devs/ata/`](https://github.com/ApolloTeam-dev/AROS/tree/master-new/rom/devs/ata)
```suggestion
- [`rom/devs/ata/`](https://github.com/ApolloTeam-dev/AROS/tree/master/rom/devs/ata)
```

2021-03-20 13:59 UTC, MBeijer commented on docs/tasks/IDE.md
> +- [`arch/m68k-all/`](https://github.com/ApolloTeam-dev/AROS/tree/master-new/arch/m68k-all)
```suggestion
- [`arch/m68k-all/`](https://github.com/ApolloTeam-dev/AROS/tree/master/arch/m68k-all)
```

2021-03-20 13:59 UTC, MBeijer commented on docs/tasks/IDE.md
> +- [`arch/m68k-amiga/`](https://github.com/ApolloTeam-dev/AROS/tree/master-new/arch/m68k-amiga)
```suggestion
- [`arch/m68k-amiga/`](https://github.com/ApolloTeam-dev/AROS/tree/master/arch/m68k-amiga)
```

2021-03-20 13:59 UTC, MBeijer commented on docs/tasks/SD-card.md
> +- With the [`master-new`](https://github.com/ApolloTeam-dev/AROS) branch, which is the default, use `build_all.sh`.
```suggestion
- With the [`master`](https://github.com/ApolloTeam-dev/AROS) branch, which is the default, use `build_all.sh`.
```

2021-03-20 13:59 UTC, MBeijer commented on docs/tasks/SD-card.md
> +- With the [`master-new`](https://github.com/ApolloTeam-dev/AROS) branch, which is the default, use `build_all.sh`.
perhaps remove this line entirely? both scripts are available though

2021-03-20 13:59 UTC, MBeijer commented on docs/tasks/SD-card.md
> +- If you are using the [`mkapollo.sh`](https://github.com/ApolloTeam-dev/AROS/blob/v4-alynna/mkapollo.sh) script, `./mkapollo.sh kernel` suffices to build it. There are some improvements pending merg
```suggestion
- If you are using the [`mkapollo.sh`](https://github.com/ApolloTeam-dev/AROS/blob/master/mkapollo.sh) script, `./mkapollo.sh kernel` suffices to build it.
```

2021-03-20 13:59 UTC, MBeijer commented on docs/tasks/Workbook.md
> +- With the [`master-new`](https://github.com/ApolloTeam-dev/AROS) branch, which is the default, use `build_all.sh`.
```suggestion
- With the [`master`](https://github.com/ApolloTeam-dev/AROS) branch, which is the default, use `build_all.sh`.
```

2021-03-20 13:59 UTC, MBeijer commented on docs/tasks/Workbook.md
> +- If you are using the [`mkapollo.sh`](https://github.com/ApolloTeam-dev/AROS/blob/v4-alynna/mkapollo.sh) script, `./mkapollo.sh kernel` suffices to build it. There are some improvements pending merg
```suggestion
- If you are using the [`mkapollo.sh`](https://github.com/ApolloTeam-dev/AROS/blob/master/mkapollo.sh) script, `./mkapollo.sh kernel` suffices to build it.
```

2021-03-20 13:59 UTC, MBeijer commented on docs/tasks/Workbook.md
> +- [`workbench/libs/workbench/`](https://github.com/ApolloTeam-dev/AROS/tree/master-new/workbench/libs/workbench)
```suggestion
- [`workbench/libs/workbench/`](https://github.com/ApolloTeam-dev/AROS/tree/master/workbench/libs/workbench)
```

2021-03-20 13:59 UTC, MBeijer commented on docs/tasks/SD-card.md
> +[`rom/devs/sdcard/`](https://github.com/ApolloTeam-dev/AROS/tree/master-new/rom/devs/sdcard)
```suggestion
[`rom/devs/sdcard/`](https://github.com/ApolloTeam-dev/AROS/tree/master/rom/devs/sdcard)
```

2021-03-20 13:59 UTC, MBeijer commented on docs/tasks/SD-card.md
> +[`rom/devs/sdcard/sdcard_ioops.c`](https://github.com/ApolloTeam-dev/AROS/tree/master-new/rom/devs/sdcard/sdcard_ioops.c)
```suggestion
[`rom/devs/sdcard/sdcard_ioops.c`](https://github.com/ApolloTeam-dev/AROS/tree/master/rom/devs/sdcard/sdcard_ioops.c)
```

2021-03-20 15:22 UTC, MBeijer approved these changes

2021-03-20 19:43 UTC, MBeijer commented
Awaiting your approval @ronybeck

2021-03-20 20:14 UTC, AlbertoGP commented
There was today a post in the discord channel showing a roadmap for 2021:
https://discord.com/channels/726870908568076380/726871100243312650/822872181486649374

If someone else is tracking these things somewhere else, it might make more sense to put this information there, where it will be seen.

2022-03-05 13:31 UTC, closed without merging